# tasks/dns.yml - DNS record management

- name: Generate random hostname for DNS
  set_fact:
    random_hostname: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=' ~ random_hostname_length) }}"
  when: random_hostname is not defined

- name: Set DNS hostname
  set_fact:
    dns_hostname: "{{ random_hostname }}.{{ base_domain }}"
  when: dns_hostname is not defined

- name: Set KV store hostname
  set_fact:
    kv_hostname: "{{ random_hostname }}"
  when: kv_hostname is not defined

- name: Debug DNS variables
  debug:
    msg: 
      - "Random Hostname: {{ random_hostname }}"
      - "DNS Hostname: {{ dns_hostname }}"
      - "KV Hostname: {{ kv_hostname }}"
      - "Inventory Hostname: {{ inventory_hostname }}"
      - "API Endpoint: {{ cloudflare_api_endpoint }}"
      - "Zone ID: {{ base_domain_cloudflare_zone_id }}"
      - "Account ID: {{ cloudflare_account_id }}"
      - "Envoy Mappings Available: {{ envoy_mappings[inventory_hostname] is defined }}"

- name: Add DNS A records for IPv4 addresses from envoy mappings
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ base_domain_cloudflare_zone_id }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: A
      name: "{{ random_hostname }}"
      content: "{{ item }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  loop: "{{ envoy_mappings[inventory_hostname].ipv4 }}"
  when: 
    - envoy_mappings is defined
    - envoy_mappings[inventory_hostname] is defined
    - envoy_mappings[inventory_hostname].ipv4 is defined
  register: dns_a_records_result

- name: Debug DNS A records results
  debug:
    var: dns_a_records_result
  when: dns_a_records_result is defined

- name: Add DNS AAAA records for IPv6 addresses from envoy mappings
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ base_domain_cloudflare_zone_id }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: AAAA
      name: "{{ random_hostname }}"
      content: "{{ item }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  loop: "{{ envoy_mappings[inventory_hostname].ipv6 }}"
  when: 
    - envoy_mappings is defined
    - envoy_mappings[inventory_hostname] is defined
    - envoy_mappings[inventory_hostname].ipv6 is defined
  register: dns_aaaa_records_result

- name: Debug DNS AAAA records results
  debug:
    var: dns_aaaa_records_result
  when: dns_aaaa_records_result is defined

# Fallback to server's own IPs if no envoy mappings are found
- name: Add DNS A record using server IP
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ base_domain_cloudflare_zone_id }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: A
      name: "{{ random_hostname }}"
      content: "{{ ansible_default_ipv4.address }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  when: 
    - envoy_mappings is not defined or envoy_mappings[inventory_hostname] is not defined or envoy_mappings[inventory_hostname].ipv4 is not defined
    - ansible_default_ipv4.address is defined
  register: fallback_dns_a_record_result

- name: Debug fallback DNS A record result
  debug:
    var: fallback_dns_a_record_result
  when: fallback_dns_a_record_result is defined

- name: Add DNS AAAA record using server IP
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ base_domain_cloudflare_zone_id }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: AAAA
      name: "{{ random_hostname }}"
      content: "{{ ansible_default_ipv6.address }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  when: 
    - envoy_mappings is not defined or envoy_mappings[inventory_hostname] is not defined or envoy_mappings[inventory_hostname].ipv6 is not defined
    - ansible_default_ipv6.address is defined
  register: fallback_dns_aaaa_record_result

- name: Debug fallback DNS AAAA record result
  debug:
    var: fallback_dns_aaaa_record_result
  when: fallback_dns_aaaa_record_result is defined

# Additional domain DNS records
- name: Add DNS A records for IPv4 addresses from envoy mappings for additional domains
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ item[0].zone_id | default(base_domain_cloudflare_zone_id) }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: A
      name: "{{ random_hostname }}"
      content: "{{ item[1] }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  with_nested:
    - "{{ additional_domains | default([]) }}"
    - "{{ envoy_mappings[inventory_hostname].ipv4 | default([]) }}"
  when: 
    - additional_domains is defined
    - envoy_mappings is defined
    - envoy_mappings[inventory_hostname] is defined
    - envoy_mappings[inventory_hostname].ipv4 is defined
  register: additional_dns_a_records_result

- name: Add DNS AAAA records for IPv6 addresses from envoy mappings for additional domains
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ item[0].zone_id | default(base_domain_cloudflare_zone_id) }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: AAAA
      name: "{{ random_hostname }}"
      content: "{{ item[1] }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  with_nested:
    - "{{ additional_domains | default([]) }}"
    - "{{ envoy_mappings[inventory_hostname].ipv6 | default([]) }}"
  when: 
    - additional_domains is defined
    - envoy_mappings is defined
    - envoy_mappings[inventory_hostname] is defined
    - envoy_mappings[inventory_hostname].ipv6 is defined
  register: additional_dns_aaaa_records_result

# Fallback DNS records for additional domains
- name: Add fallback DNS A records for additional domains
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ item.zone_id | default(base_domain_cloudflare_zone_id) }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: A
      name: "{{ random_hostname }}"
      content: "{{ ansible_default_ipv4.address }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  loop: "{{ additional_domains | default([]) }}"
  when: 
    - additional_domains is defined
    - (envoy_mappings is not defined or envoy_mappings[inventory_hostname] is not defined or envoy_mappings[inventory_hostname].ipv4 is not defined)
    - ansible_default_ipv4.address is defined
  register: additional_fallback_dns_a_records_result

- name: Add fallback DNS AAAA records for additional domains
  uri:
    url: "{{ cloudflare_api_endpoint }}/zones/{{ item.zone_id | default(base_domain_cloudflare_zone_id) }}/dns_records"
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body_format: json
    body:
      type: AAAA
      name: "{{ random_hostname }}"
      content: "{{ ansible_default_ipv6.address }}"
      ttl: 1
      proxied: false
    status_code: [200, 201]
  delegate_to: localhost
  loop: "{{ additional_domains | default([]) }}"
  when: 
    - additional_domains is defined
    - (envoy_mappings is not defined or envoy_mappings[inventory_hostname] is not defined or envoy_mappings[inventory_hostname].ipv6 is not defined)
    - ansible_default_ipv6.address is defined
  register: additional_fallback_dns_aaaa_records_result

- name: Debug additional domains DNS records results
  debug:
    msg:
      - "Additional A Records Result: {{ additional_dns_a_records_result | default('Not created') }}"
      - "Additional AAAA Records Result: {{ additional_dns_aaaa_records_result | default('Not created') }}"
      - "Additional Fallback A Records Result: {{ additional_fallback_dns_a_records_result | default('Not created') }}"
      - "Additional Fallback AAAA Records Result: {{ additional_fallback_dns_aaaa_records_result | default('Not created') }}"
  when: additional_domains is defined
