---
# tasks/kv.yml - KV store updates

- name: Extract random string from API URL
  set_fact:
    api_random_string: "{{ outline_api_info.apiUrl | regex_search('/([^/]+)$') | regex_replace('/', '') }}"
  when: outline_api_info is defined

- name: Debug API random string
  debug:
    var: api_random_string
  when: api_random_string is defined

- name: Update Cloudflare KV store with API endpoint
  uri:
    url: "{{ cloudflare_api_endpoint }}/accounts/{{ cloudflare_account_id }}/storage/kv/namespaces/{{ cloudflare_api_kv_namespace }}/values/{{ random_hostname }}"
    method: PUT
    headers:
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body: "https://{{ random_hostname }}-api.{{ api_domain }}/{{ api_random_string | default('') }}"
    status_code: 200
  delegate_to: localhost
  when: api_random_string is defined

- name: Update Cloudflare KV store with Prometheus endpoint
  uri:
    url: "{{ cloudflare_api_endpoint }}/accounts/{{ cloudflare_account_id }}/storage/kv/namespaces/{{ cloudflare_prom_kv_namespace }}/values/{{ random_hostname }}"
    method: PUT
    headers:
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    body: "https://{{ random_hostname }}-prom.{{ prom_domain }}"
    status_code: 200
  delegate_to: localhost
