---
# tasks/migrate/verify_source.yml - Source server verification tasks

# Check source server status
- name: Verify source server exists
  uri:
    url: "{{ cloudflare_api_endpoint }}/accounts/{{ cloudflare_account_id }}/storage/kv/namespaces/{{ cloudflare_api_kv_namespace }}/values/{{ source_kv_hostname }}"
    method: GET
    headers:
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    status_code: [200, 404]
  delegate_to: localhost
  register: source_server
  failed_when: false
  run_once: true

- name: Get source server Prometheus endpoint
  uri:
    url: "{{ cloudflare_api_endpoint }}/accounts/{{ cloudflare_account_id }}/storage/kv/namespaces/{{ cloudflare_prom_kv_namespace }}/values/{{ source_kv_hostname }}"
    method: GET
    headers:
      X-Auth-Email: "{{ cloudflare_email }}"
      X-Auth-Key: "{{ cloudflare_api_token }}"
    status_code: [200, 404]
  delegate_to: localhost
  register: source_prom
  failed_when: false
  run_once: true

# Stop source server containers
- name: Stop Outline containers on source server
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop:
    - watchtower
    - shadowbox
  become: yes
  when: inventory_hostname == source_hostname
